name: Print Commit Message


on:
  push:
    branches:
      - master
jobs:
  print-commit-info:
    runs-on: ubuntu-lastest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Print commit information
        run: |
          git log -1 --pretty=format:"Commit: %H%nAuthor: %an%nDate: %ad%nMessage: %s
      
        
        
      
      
